version: '3'
services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/db:/var/lib/mysql

  myadmin:
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"